# Generated by Django 6.0.1 on 2026-01-10 00:14

import products.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=products.utils.product_image_upload_path),
        ),
    ]
